name: Windows MSYS Build

on:
  push:
  pull_request:

env:
  GH_CACHE_KEY: 7

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        env: [
          #{bits: 32, build_type: Debug,   arch: i686,   arch_zip: x86},
          {bits: 64, build_type: Debug,   arch: x86_64, arch_zip: x64},
          {bits: 32, build_type: Release, arch: i686,   arch_zip: x86},
          {bits: 64, build_type: Release, arch: x86_64, arch_zip: x64}
        ]
    name: ${{matrix.env.build_type}} ${{matrix.env.bits}} bits
    defaults:
      run:
        shell: msys2 {0}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW${{matrix.env.bits}}
          install:
            mingw-w64-${{matrix.env.arch}}-ninja
            mingw-w64-${{matrix.env.arch}}-gcc
            mingw-w64-${{matrix.env.arch}}-cmake
            mingw-w64-${{matrix.env.arch}}-make
            mingw-w64-${{matrix.env.arch}}-SDL2
            mingw-w64-${{matrix.env.arch}}-SDL2_image
            mingw-w64-${{matrix.env.arch}}-SDL2_net
            mingw-w64-${{matrix.env.arch}}-SDL2_mixer
            mingw-w64-${{matrix.env.arch}}-boost
            mingw-w64-${{matrix.env.arch}}-lld
            mingw-w64-${{matrix.env.arch}}-libbacktrace
            mingw-w64-${{matrix.env.arch}}-libvpx
            mingw-w64-${{matrix.env.arch}}-nasm
            mingw-w64-${{matrix.env.arch}}-yasm
            mingw-w64-${{matrix.env.arch}}-zlib
            base-devel
            wget
            unzip
            git
            bash
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            ${{ github.workspace }}\downloads
            ${{ github.workspace }}\ffmpeg
          key: MSYS-${{matrix.env.arch}}-${{ env.GH_CACHE_KEY }}
      - name: SDL2 binaries -- download
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir downloads
          wget https://github.com/libsdl-org/SDL_image/releases/download/release-2.6.3/SDL2_image-2.6.3-win32-${{matrix.env.arch_zip}}.zip -O downloads/SDL2_image.zip
          wget https://github.com/libsdl-org/SDL_mixer/releases/download/release-2.6.3/SDL2_mixer-2.6.3-win32-${{matrix.env.arch_zip}}.zip -O downloads/SDL2_mixer.zip
      - name: ffmpeg -- download
        if: steps.cache.outputs.cache-hit != 'true'
        run: git clone --depth 1 --branch n5.1 https://git.ffmpeg.org/ffmpeg.git ffmpeg
      - name: ffmpeg -- configure
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          ./configure --enable-shared --prefix=/mingw${{matrix.env.bits}} \
          --disable-everything \
          --enable-swscale \
          --enable-swresample \
          --enable-zlib \
          --enable-libvpx \
          --enable-libvorbis \
          --enable-demuxer=avi,rawvideo,bink,matroska \
          --enable-decoder=png,rawvideo,bink,binkaudio_dct,vorbis,opus,vp8,vp9 \
          --enable-parser=png,vp9 \
          --enable-filter=aresample,aformat \
          --enable-protocol=file \
          --disable-d3d11va \
          --disable-dxva2 \
          --disable-vulkan \
          --disable-doc --disable-ffplay --disable-ffprobe --disable-ffmpeg \
          --disable-static --disable-bzlib --disable-libopenjpeg --disable-iconv
        working-directory: ffmpeg
      - name: ffmpeg -- build
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mingw32-make -j4
        working-directory: ffmpeg
      - name: ffmpeg -- install
        run: |
          mingw32-make install
        working-directory: ffmpeg
      - name: perimeter -- create build dir
        run: mkdir build
      - name: perimeter -- configure build
        run: cmake -G Ninja .. -DCMAKE_BUILD_TYPE=${{matrix.env.build_type}}
        working-directory: build
      - name: perimeter -- make
        run: ninja
        working-directory: build
      - name: perimeter -- prepare artifact folder
        run: |
          unzip downloads/SDL2_image.zip -d /SDL2_image
          unzip downloads/SDL2_mixer.zip -d /SDL2_mixer
          mkdir -p perimeter/bin
          cp /mingw${{matrix.env.bits}}/bin/SDL2.dll perimeter/bin/
          cp /mingw${{matrix.env.bits}}/bin/SDL2_net.dll perimeter/bin/
          cp /mingw${{matrix.env.bits}}/bin/libgcc_*.dll perimeter/bin/
          cp /mingw${{matrix.env.bits}}/bin/libstdc++-6.dll perimeter/bin/
          cp /mingw${{matrix.env.bits}}/bin/libwinpthread-1.dll perimeter/bin/
          #cp /mingw${{matrix.env.bits}}/bin/libbacktrace-0.dll perimeter/bin/
          cp /mingw${{matrix.env.bits}}/bin/avcodec-*.dll perimeter/bin/
          cp /mingw${{matrix.env.bits}}/bin/avfilter-*.dll perimeter/bin/
          cp /mingw${{matrix.env.bits}}/bin/avformat-*.dll perimeter/bin/
          cp /mingw${{matrix.env.bits}}/bin/avutil-*.dll perimeter/bin/
          cp /mingw${{matrix.env.bits}}/bin/swscale-*.dll perimeter/bin/
          cp /mingw${{matrix.env.bits}}/bin/swresample-*.dll perimeter/bin/
          cp /mingw${{matrix.env.bits}}/bin/zlib1.dll perimeter/bin/
          cp /SDL2_image/*.dll perimeter/bin/
          cp /SDL2_mixer/*.dll perimeter/bin/
          cp build/Source/perimeter.exe perimeter/bin/
      - name: perimeter -- strip binary
        run: strip -g -x perimeter/bin/perimeter.exe
      - uses: actions/upload-artifact@v1
        with:
          name: Perimeter MSYS ${{matrix.env.build_type}} ${{matrix.env.bits}} bits
          path: perimeter/bin/